### ISSUE TITLE
Результаты опроса пользователей

### ISSUE THREAD

**Issue by lixich** [GameDevTeamPerm/Analytics#12]
Информация о пользователях системы: преподаватели, студенты. 
Зачем им приложение?
Какие проблемы решает?
Как раньше проблему решали?
Пожелания к приложения (платформа, доступ).
Ваши устройства (смартфон, ноутбук).
Дополнить существующий опросник.
[](https://docs.google.com/spreadsheets/d/10X9LuJpkTtoaLv4LEwJxskx4a-mxf5iuUBg7EG-gUJw/edit#gid=1715842611)
ПОКАЗАТЬ ОПРОСНИК ВНАЧАЛЕ АЛЕКСЕЮ

**Comment by lixich** [comment]
https://docs.google.com/spreadsheets/d/10X9LuJpkTtoaLv4LEwJxskx4a-mxf5iuUBg7EG-gUJw/edit#gid=1715842611

**Comment by TanakiSinitsu** [comment]
Ссылка на опросник. Жду подтверждения 
https://goo.gl/forms/VeFKiEaEfIc6mpM83

**Comment by Smalex911** [comment]
Можно добавить пункт "как к вам можно обращаться" и "напишите свою электронную почту, если хотите поучаствовать в тестировании игры"

**Comment by lixich** [comment]
Надо вверху написать попонятнее для чего игра. Например, мы разрабатываем симулятор командной разработки, где Вы ИТ-менеджер проекта, Ваша задача собрать виртуальную команду и реализовать все требования заказчика. Планируется реализация такого симулятора в рамках ученого процесса, поэтому мы бы хотели знать, как Вам было бы удобнее работа с таким приложением в рамках учебного процесса.

**Comment by lixich** [comment]
И не бизнес-игра, а деловая игра лучше

**Comment by Smalex911** [comment]
Мне кажется ты предложил слишком много текста. Лучше оставить так как есть, потому что дальше идут вопросы а что вы думаете когда слышите it-manager и прочее. Ну это чисто мое предложение, подумайте, я не настаиваю, может согласитесь

**Comment by Smalex911** [comment]
Еще я бы хотел после сбора ответов увидеть какую-нибудь аналитику, что у студентов в приоритете, что отклоняют категорично и прочее

**Comment by lixich** [comment]
Про аналитику поддерживаю

**Comment by lixich** [comment]
Про описание, нужно найти баланс, просто я не понял по описанию для чего вообще эта игра, я подумал, что просто для развлечения. Если для развлечения, то я сразу выбрал бы мобилку. А вот если для учебных целей, я бы долго думал. Нужно, чтобы респонденты поняли, что такая деловая игра будет проходить в рамках учебного процесса

**Comment by Smalex911** [comment]
Согласен, нотку учебного процесса надо добавить

**Comment by TanakiSinitsu** [comment]
Поняла, постараюсь к вечеру завтрашнего дня  собрать статистику небольшую

**Comment by lixich** [comment]
Провести опрос по каждому курсу (1, 2, 3, 4) по  5 человек (чтоб, как минимум, половина была с ПИ) . Подвести результаты, как пользователи хотели бы использовать нашу игру в учебном процессе. Их пожелания, требования.

**Comment by TanakiSinitsu** [comment]
https://docs.google.com/forms/d/1_qsEqCX7ONqMXSxFcS7lmUPzM3c0f0CeCqt56epy1mA/edit?usp=sharing
