### ISSUE TITLE
Обзор плтаформ wpf и web

### ISSUE THREAD

**Issue by lixich** [GameDevTeamPerm/Analytics#14]
Сравнительный анализ:
1. Доступ к библиотекам для рисования сцен, меню, кнопок, рубильников.
2. Реализации анимированный картинки.
3. Возможность рисования разных графиков 2д, 3д, диагармма ганта. Анимированное движение графиков.
4. Звуковая поддержка.
5. Требования к оборудованию.

**Comment by lixich** [comment]
@Smalex911 результат выполнения задания есть какой-то?

**Comment by Smalex911** [comment]
Средства для Web платформ хорошие все платные, бесплатные только с урезанными функциями, и предоставляют не те функции которые нам нужны, они все обычно предоставляют интерфейс диаграммы какой-то уже установленной схемы плана, редактировать данные на графике сложно.
В нативном приложении (wpf) мы сможем сделать, то что хотим, любой элемент управления настроить под свои нужды. Также как и с web, хорошие средства диаграммы Ганта платные, однако я нашел пару бесплатных средств, которые думаю могут подойти под наши нужды [wpfgantt](http://wpfgantt.codeplex.com/documentation) и [nGantt](https://github.com/danwallentin/nGantt)

Про анимацию я думаю в настольном приложении мы сможем лучше добиться ее реализации, нежели в web. Если посмотреть на любые сайты, то они обычно статичны, а если используется анимация, то она достигается за счет JS скриптов, что мы вряд ли будем делать в нашей игре, потому что это очень затратно по ресурсам и времени на реализацию (+ у нас нет хороших специалистов в этой области)

Анимация картинки в wpf достигается за счет изменения картинки в установленное время, [вот](https://stackoverflow.com/questions/29282137/wpf-animate-image-source-change) пример, как это выглядит в коде.

**Comment by lixich** [comment]
Отлично
